name: Issue Validator Commenter
description: |
  This action comments on a pull request with a list of issues found in the commit messages. 
  It is used to validate issue summaries and descriptions in commit messages.
author: Josef Karamon
# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: git-commit
  color: blue

inputs:
  issues:
    description: Comma separated list of issues found in commit messages
    required: false
    default: ''
  pr-number:
    description: Pull request number
    required: true
    default: ''

runs:
  using: node20
  main: dist/index.js
