name: Issue PR Commenter
description: Creates a PR comment if the issue is incompletely specified.
author: Josef Karamon
# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: git-commit
  color: blue

inputs:
  issues:
    description: Comma separated list of issues
    required: false
    default: ''
  pr-number:
    description: Pull request number
    required: true
    default: ''
  pr-title-regex:
    description: Regular expression to match the PR title. Only PRs with a title matching this regex will be validated.
    required: false
    default: '.*'
  fail-when-no-issues:
    description: Fail the action if no issues are provided
    required: false
    default: 'false'

runs:
  using: node20
  main: dist/index.js
