name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pr-number: ${{ github.event.pull_request.number }}
          data-separator: '\n'
          issue-pattern: '\FXDX-\d+\b'

      - name: Print Output - Commit Messages
        id: output-commit-messages
        run: echo "${{ steps.test-action.outputs.commit-messages }}"
      - name: Print Output - Issues
        id: output-issues
        run: echo "${{ steps.test-action.outputs.issues }}"
      - name: Print Output - Files
        id: output-files
        run: echo "${{ steps.test-action.outputs.files }}"

      - name: Print Output - Patches
        id: output-patches
        run: echo "$PATCHES"
        env:
          PATCHES: ${{ steps.test-action.outputs.patches }}
      - name: Print Output - Raw Files
        id: output-raw-files
        run: echo "$RAW_FILES"
        env:
          RAW_FILES: ${{ steps.test-action.outputs.raw-files }}
